Repository SiEPIC/UBC-ELEC413-2025, pull requests merged in 2025-02, with the labels that each got.

#17 draft for chip2
  submissions/ELEC413_CheyenneTu.gds
Labels: greeted

#41 Chip 2 Design and Report
  submissions/ELEC413_BriannaGopaul.gds
  submissions/ELEC413_BriannaGopaul_DraftReportC1,C2.pdf
Labels: greeted

#37 Ella's Chip 2 Final Layout and Report Draft
  submissions/ELEC413_111homell111_MZI2.gds
Labels: greeted

#34 Added Initial Chip2 Draft
  submissions/ELEC413_IanRPang_Chip2.gds
  submissions/ELEC413_Report_IanRPang.pdf
Labels: greeted

#33 Design for Chip2
  submissions/ELEC413_YufanZhou_C2.docx
  submissions/ELEC413_Yufanabc_C2.gds
Labels: greeted

#32 draft1
  submissions/ELEC_413_ZheqingYan.gds
  submissions/Ebeam_ELEC413_Zheqing_Yan.gds
Labels: greeted

#31 Add first draft UNFINSIHED
  submissions/ELEC413_LucasH.gds
Labels: greeted

#1 Chip2 Design
  submissions/ELEC413_Wangchen.gds
Labels: greeted

#4 Chip design 2 gds file
  submissions/EBeam_ELEC413_JiahaoYan.pdf
  submissions/ELEC413_JiahaoYan_withinput.gds
Labels: greeted

#6 Chip 2 draft layout
  submissions/ELEC413_FrankJin_Chip2.gds
  submissions/ELEC413_Project_Report_FrankJin.pdf
Labels: greeted

#26 Add Chip 2 draft file
  submissions/ELEC413_SherwinTiu.gds
  submissions/ELEC413_SherwinTiu.pdf
Labels: greeted

#27 Update Chip 2 Design
  submissions/ELEC413_LeviV.oas
Labels: greeted

#29 First Draft of Chip 2
  submissions/ELEC413_Kris_Kirkwood_Report_Draft.pdf
  submissions/ELEC_413_KrisKirkwood_Report.pdf
  submissions/Elec413_Kris-Kirk.oas
Labels: greeted

#46 Updated pull
  submissions/ELEC413_ITAIBOSS_C2.gds
Labels: greeted

#14 Pull Request for Feb 10th
  submissions/ELEC413_oliverkis_V2.gds
Labels: greeted

#8 draft chip2
  submissions/EBeam_ELEC413_emilymuller.gds
Labels: greeted

#15 Add files via upload
  submissions/ELEC413_OwenL.docx
  submissions/ELEC413_OwenL1N_Chip2New.gds
Labels: greeted

#28 Chip 2 Design
  submissions/ELEC413_julianaangel.gds
Labels: greeted

#49 chip 2 design
  submissions/ELEC413_GAOYANG.gds
  submissions/ELEC413_chip2_report.pdf
Labels: greeted

#54 Chip 2 layout
  submissions/ELEC413_HaomingGao.gds
Labels: greeted

#58 Initial Design for Chip 2
  submissions/Elec413_ltousign23_chip2.gds
Labels: greeted

#61 Delete ELEC413_Bhav_Gosal02_MZI.gds
  submissions/ELEC413_Bhav_Gosal02_MZI.gds
Labels: bug, greeted

#30 Chip2
  submissions/ELEC413_RuihanZhu_CHIP2.gds
Labels: bug, greeted

#43 Chip 2 update
  submissions/ELEC413_PaigeHall.gds
Labels: bug

#63 Revert "Chip 2 update"
  submissions/ELEC413_PaigeHall.gds
Labels: greeted
